package:
  name: "tinerator"
  version: "1.0.0"

#source:
#  git_rev: v1.0.0
#  git_url: https://github.com/lanl/tinerator

source:
  path: ./

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - gdal
    - jupyter
    - ipykernel
    - requests
    - netCDF4

about:
  home: https://github.com/lanl/tinerator
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "tinerator summary"

extra:
  recipe-maintainers:
    - daniellivingston