name: Docker

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ees16/tinerator:dev
          file: Dockerfile

      - name: Image digest
        run: |
          echo "SUCCESS: Docker build successful. Finished with digest:"
          echo ${{ steps.docker_build.outputs.digest }}

      - name: Build Documentation
        run: |
          mkdir public/ &&
          docker run \
            -v $(pwd)/public:/home/feynman/public/ \
            ees16/tinerator:dev \
            /bin/bash -c \
            'cd ~/tinerator/ && python -m pip install ".[docs]" && make -C docs/ html && cp -r docs/_build/html/ ~/public/'

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public